layout_spectrum: 1
name: Beverly Jane Properties Inc.
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.6799621
  lightness: 0.8347386
  saturation: 0.7529511
  rhythmicContrast: 0.4443507
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.7875211
