layout_spectrum: 0.2192243
typography_spectrum: 0.760732
color:
  lightness: 0.3499157
  brandStrength: 0.6799621
  saturation: 0.5042158
  rhythmicContrast: 0.1931538
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Beverly Jane Properties Inc.
